/*
 * Copyright (c) 2019-2023 Huazhong University of Science and Technology
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation;
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * Authors: Pengyu Liu <eic_lpy@hust.edu.cn>
 *          Hao Yin <haoyin@uw.edu>
 *          Muyuan Shen <muyuan_shen@hust.edu.cn>
 */

#pragma once
#include "ns3/ai-module.h"
#include "ns3/core-module.h"
#include "ns3/ff-mac-common.h"

namespace ns3
{
#define MAX_RBG_NUM 32

/**
 * Schema hash generated by ComputeNs3AiMsgSchemaHash() from:
 *   struct CqiFeature (version 1, size 1)
 *   fields:
 *     wbCqi  (UInt8, offset=0, size=1, count=1)
 */
inline constexpr uint64_t CQI_FEATURE_SCHEMA_HASH   = 0x71d9967300778de2ULL;
inline constexpr uint32_t CQI_FEATURE_SCHEMA_VERSION = 1;

/**
 * Schema hash generated by ComputeNs3AiMsgSchemaHash() from:
 *   struct CqiPredicted (version 1, size 1)
 *   fields:
 *     new_wbCqi  (UInt8, offset=0, size=1, count=1)
 */
inline constexpr uint64_t CQI_PREDICTED_SCHEMA_HASH   = 0x51bbbdda75a299a5ULL;
inline constexpr uint32_t CQI_PREDICTED_SCHEMA_VERSION = 1;

/**
 * \brief The feature of cqi.
 *
 * The feature of DL training (in this example, feature of cqi)
 * shared between ns-3 and python with the same shared memory
 * using the ns3-ai model.
 */
struct CqiFeature
{
    uint8_t wbCqi; ///< wide band cqi
};

/**
 * \brief The prediction of cqi.
 *
 * The prediction of DL training (in this example, prediction of cqi)
 * calculated by python and put back to ns-3 with the shared memory.
 */
struct CqiPredicted
{
    uint8_t new_wbCqi;
};

/**
 * \brief A class to predict CQI(Channel Quality Indication).
 *
 * This class shared memory with python by the same id.
 * It set data through member function 'Set[xxx]()',
 * and put them into the shared memory, using python to calculate,
 * and got prediction through member function 'Get[xxx]()'.
 */
class CQIDL : public Object
{
  public:
    CQIDL();
    ~CQIDL() override;
    static TypeId GetTypeId();

    void SetWbCQI(uint8_t cqi);
    uint8_t GetWbCQI();
};

template <>
struct Ns3AiMsgTypeSchemaDefaults<CqiFeature>
{
    static constexpr uint64_t SchemaHash = CQI_FEATURE_SCHEMA_HASH;
    static constexpr uint32_t SchemaVersion = CQI_FEATURE_SCHEMA_VERSION;
};

template <>
struct Ns3AiMsgTypeSchemaDefaults<CqiPredicted>
{
    static constexpr uint64_t SchemaHash = CQI_PREDICTED_SCHEMA_HASH;
    static constexpr uint32_t SchemaVersion = CQI_PREDICTED_SCHEMA_VERSION;
};

} // namespace ns3
