/*
 * Copyright (c) 2023 Huazhong University of Science and Technology
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation;
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * Author: Muyuan Shen <muyuan_shen@hust.edu.cn>
 */

#ifndef APB_H
#define APB_H

#include <cstdint>
#include <ns3/ns3-ai-msg-interface.h>

/**
 * Schema hash generated by ComputeNs3AiMsgSchemaHash() from:
 *   struct EnvStruct (version 1, size 8)
 *   fields:
 *     env_a  (UInt32, offset=0, size=4, count=1)
 *     env_b  (UInt32, offset=4, size=4, count=1)
 */
inline constexpr uint64_t ENV_STRUCT_SCHEMA_HASH   = 0xa66c066d6d9b046fULL;
inline constexpr uint32_t ENV_STRUCT_SCHEMA_VERSION = 1;

/**
 * Schema hash generated by ComputeNs3AiMsgSchemaHash() from:
 *   struct ActStruct (version 1, size 4)
 *   fields:
 *     act_c  (UInt32, offset=0, size=4, count=1)
 */
inline constexpr uint64_t ACT_STRUCT_SCHEMA_HASH   = 0x879b048959e5394aULL;
inline constexpr uint32_t ACT_STRUCT_SCHEMA_VERSION = 1;

struct EnvStruct
{
    uint32_t env_a;
    uint32_t env_b;
};

struct ActStruct
{
    uint32_t act_c;
};

namespace ns3
{

template <>
struct Ns3AiMsgTypeSchemaDefaults<::EnvStruct>
{
    static constexpr uint64_t SchemaHash = ::ENV_STRUCT_SCHEMA_HASH;
    static constexpr uint32_t SchemaVersion = ::ENV_STRUCT_SCHEMA_VERSION;
};

template <>
struct Ns3AiMsgTypeSchemaDefaults<::ActStruct>
{
    static constexpr uint64_t SchemaHash = ::ACT_STRUCT_SCHEMA_HASH;
    static constexpr uint32_t SchemaVersion = ::ACT_STRUCT_SCHEMA_VERSION;
};

} // namespace ns3

#endif // APB_H
